apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels: # You can add your own keys for labels here
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      